spring.application.name=ayrfu

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/ayrfu
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.show-sql=true
spring.jpa.open-in-view=true
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG

# JWT configuration
jwt.secret=FOt6S1r2jQwY5hX0pK8nL3mD4bE7aVcZgU9iT2oP3sN6xR1yM7wG0zH4vB5uJ8PHlK
jwt.expiration=86400000

# File Storage Configuration
file.upload-dir=./uploads